"""Simulation-based allocation of equity value across the cap table.

What it is for
--------------
The closed-form OPM (``waterfall.allocate_waterfall``) prices each class as a
sum of Black-Scholes call spreads. That is exact, and it is exact *because* two
things hold: the payoff is piecewise linear in terminal equity value, and
terminal equity value is a single lognormal. Where both hold, simulating is
strictly worse than the closed form — same answer, plus noise.

They stop holding when the exit is not one lognormal. A company with a credible
IPO case at five years and a credible trade-sale case at two does not have one
expected exit: it has two, with different horizons and different volatilities,
and the common stock's value depends on the *whole distribution* within each,
not just on its mean. PWERM answers that with point estimates per scenario —
one exit value, no uncertainty around it — and the hybrid method blends a PWERM
point estimate with an OPM by a weight somebody chose.

This module is the thing between them: discrete scenarios, each carrying its own
horizon and volatility, with the equity evolving lognormally *inside* each. It
reduces exactly to the OPM when there is one scenario, which is how it is
tested, and to something PWERM-shaped as the volatilities go to zero.

Reproducibility
---------------
A 409A that returns a different fair market value each time it is run is
indefensible — a reviewer re-running it must get the concluded figure back, and
so must the analyst defending it three years later in an audit. So the draw is
seeded, the seed defaults to a constant, the seed travels in the result, and the
sequence is generated by this module's own PRNG instance rather than the global
one, which anything else in the process could have advanced.

The estimator also reports its own standard error, because a simulated figure
without one is a number pretending to be exact. `paths` is chosen so that error
is small relative to the rounding on a per-share conclusion, and the caller can
see whether it was.

Variance reduction
------------------
Antithetic variates: each normal draw Z is used with −Z as well. The payoff is
monotone in the draw, so the pair is negatively correlated and the mean of the
pair has materially lower variance than two independent draws. It costs one
extra waterfall evaluation and no extra randomness, and it makes the estimate
symmetric in the draw — a property worth having on its own, since it removes the
chance that a particular seed leans high or low overall.
"""

from __future__ import annotations

import math
import random

from .errors import EngineInputError
from .waterfall import _normalize, _segments

#: Simulated paths when the caller does not say. Chosen against the conclusion
#: rather than for a round number: a per-share figure is reported to four
#: decimals, and on the cap tables this platform sees, 20,000 antithetic pairs
#: puts the standard error of the common per-share estimate roughly an order of
#: magnitude below that last digit. Fewer is defensible for exploration; this is
#: the default because the default is what a deliverable is built on.
DEFAULT_PATHS = 20_000

#: Ceiling on one request. The inner loop is O(paths x segments x classes) in
#: pure Python and this endpoint is synchronous, so the bound is a latency bound
#: rather than a modelling one.
MAX_PATHS = 200_000

#: The seed a valuation uses unless one is recorded on it. Any constant would
#: do; what matters is that it is *a* constant and that it is reported.
DEFAULT_SEED = 409

#: Most scenarios anyone has a defensible story for.
MAX_SCENARIOS = 20


def _num(value, name: str, *, positive: bool = False, nonneg: bool = False) -> float | None:
    if value is None:
        return None
    try:
        out = float(value)
    except (TypeError, ValueError):
        raise EngineInputError(f"{name} must be a number") from None
    if not math.isfinite(out):
        raise EngineInputError(f"{name} must be finite")
    if positive and out <= 0:
        raise EngineInputError(f"{name} must be positive")
    if nonneg and out < 0:
        raise EngineInputError(f"{name} must be >= 0")
    return out


def _resolve_scenarios(raw, *, t: float, sigma: float) -> list[dict]:
    """Scenario list, defaulted to the single lognormal the OPM assumes.

    An absent or empty list is not an error: it is the ordinary case, and the
    single scenario it produces is what makes this method reduce to the OPM.
    """
    if raw is None:
        return [{"name": "Base", "probability": 1.0, "t": t, "sigma": sigma}]
    if not isinstance(raw, list) or not raw:
        raise EngineInputError("monte_carlo.scenarios must be a non-empty list when provided")
    if len(raw) > MAX_SCENARIOS:
        raise EngineInputError(f"monte_carlo.scenarios accepts at most {MAX_SCENARIOS} scenarios")

    out: list[dict] = []
    for i, entry in enumerate(raw):
        if not isinstance(entry, dict):
            raise EngineInputError(f"monte_carlo.scenarios[{i}] must be an object")
        prob = _num(entry.get("probability"), f"scenarios[{i}].probability", nonneg=True)
        if prob is None:
            raise EngineInputError(f"monte_carlo.scenarios[{i}].probability is required")
        # Each scenario may override the horizon and the volatility; a trade
        # sale in two years is not the same distribution as an IPO in five, and
        # collapsing them onto one pair of assumptions is exactly what this
        # method exists to avoid.
        out.append(
            {
                "name": str(entry.get("name") or f"Scenario {i + 1}"),
                "probability": prob,
                "t": _num(entry.get("years_to_exit"), f"scenarios[{i}].years_to_exit", positive=True) or t,
                "sigma": _num(entry.get("volatility"), f"scenarios[{i}].volatility", positive=True) or sigma,
            }
        )

    total = sum(s["probability"] for s in out)
    if total <= 0:
        raise EngineInputError("monte_carlo.scenarios probabilities must sum to a positive number")
    # Normalised rather than refused: probabilities that sum to 0.999 are a
    # rounding artefact of an analyst's spreadsheet, not a modelling error, and
    # `pwerm` already takes the same view of the same input.
    for s in out:
        s["probability"] /= total
    return out


def _common_payoff_factory(classes: list[dict]):
    """A fast evaluator of every class's payoff at a given exit value.

    The breakpoint segments are built once and reused for every path. Building
    them per path — which calling ``exit_allocation`` in the loop would do —
    is the difference between a simulation that runs in a second and one that
    does not finish inside a request.

    Returned as flat parallel lists rather than the dicts ``_segments``
    produces, because this runs tens of thousands of times and attribute and
    hash lookups dominate at that count.
    """
    segments = _segments(classes)
    index = {c["name"]: i for i, c in enumerate(classes)}
    lows = [seg["from"] for seg in segments]
    # `None` (unbounded) becomes infinity, so the inner loop has no branch.
    highs = [math.inf if seg["to"] is None else seg["to"] for seg in segments]
    slopes = [[(index[name], frac) for name, frac in seg["participants"].items()] for seg in segments]

    def payoff(exit_value: float, into: list[float]) -> None:
        """Adds each class's share of `exit_value` into `into`, in place."""
        for lo, hi, participants in zip(lows, highs, slopes):
            if exit_value <= lo:
                # Segments are ordered, so nothing above this one is reached
                # either — the exit value ran out inside the previous tranche.
                break
            width = min(exit_value, hi) - lo
            for i, fraction in participants:
                into[i] += width * fraction

    return payoff


def allocate_monte_carlo(
    equity_value: float,
    inputs: dict,
    *,
    t: float,
    r: float,
    sigma: float,
) -> dict:
    """Allocate `equity_value` across the cap table by simulation.

    Risk-neutral, like the OPM it generalises: the equity value drifts at the
    risk-free rate and each scenario's payoff is discounted back at the same
    rate. That is what makes value conserve — the probability-weighted, present
    value of every class's payoff sums to `equity_value` — and it is what lets
    the single-scenario case be checked against the closed form.
    """
    if equity_value <= 0:
        raise EngineInputError("equity_value must be positive for the Monte Carlo allocation")
    raw_classes = inputs.get("share_classes")
    if not isinstance(raw_classes, list) or not raw_classes:
        raise EngineInputError(
            "allocation_method 'monte_carlo' requires inputs.share_classes (the cap table) — "
            "simulating a payoff needs the payoff structure it is simulating"
        )
    classes = _normalize(raw_classes)

    config = inputs.get("monte_carlo")
    if config is not None and not isinstance(config, dict):
        raise EngineInputError("inputs.monte_carlo must be an object")
    config = config or {}

    paths = int(_num(config.get("paths"), "monte_carlo.paths", positive=True) or DEFAULT_PATHS)
    if paths > MAX_PATHS:
        raise EngineInputError(f"monte_carlo.paths accepts at most {MAX_PATHS}")
    # Antithetic pairs, so the count is even by construction and the reported
    # figure is what was actually run rather than what was asked for.
    pairs = max(1, paths // 2)
    seed = int(_num(config.get("seed"), "monte_carlo.seed") or DEFAULT_SEED)
    scenarios = _resolve_scenarios(config.get("scenarios"), t=t, sigma=sigma)

    payoff = _common_payoff_factory(classes)
    n = len(classes)
    common_at = [i for i, c in enumerate(classes) if c["kind"] == "common"]
    common_shares = sum(c["shares"] for c in classes if c["kind"] == "common")
    if common_shares <= 0:  # pragma: no cover - `_normalize` already refuses both ways in
        # Kept as a divide-by-zero backstop for `common_per_share`, but not
        # reachable: `_normalize` requires at least one class of kind "common"
        # and requires every class's `shares` to be positive, so the sum here
        # cannot be zero. Both refusals are pinned in
        # `test_monte_carlo_precision.TestTheCapTableItNeeds`.
        raise EngineInputError("share_classes must include at least one common class with shares")

    rng = random.Random(seed)
    totals = [0.0] * n
    # Precision of the *common* payoff only — it is the figure the conclusion
    # rests on, and the one whose precision a reviewer asks about.
    #
    # Accumulated per scenario rather than into one pooled pair of moments,
    # because the scenarios are not draws from a common distribution: each has
    # its own horizon, volatility and weight. The estimator is
    # `Σ pᵢ·mean(scenario i)`, and the scenarios are drawn independently, so its
    # variance is `Σ pᵢ²·Var(mean(scenario i))` — a sum of per-scenario terms
    # that no pooled moment can be unwound into.
    #
    # Pooling them got both halves of `Var = E[c²] − E[c]²` wrong, and by
    # different factors: weighting each draw by `pᵢ` and then dividing by the
    # count of *all* draws made the reported mean `1/len(scenarios)` of the true
    # probability-weighted mean, so the subtracted term was off by that squared.
    # The residue was large and positive — two identical scenarios, which are by
    # construction the same distribution as one, reported a standard error that
    # did not fall as `1/√n`, and a deterministic payoff (σ→0) reported a
    # substantial error around a figure that was exact. Single-scenario runs
    # were unaffected, which is why the closed-form oracle never caught it.
    estimator_variance = 0.0
    per_scenario: list[dict] = []

    for scenario in scenarios:
        s_t, s_sigma, prob = scenario["t"], scenario["sigma"], scenario["probability"]
        drift = (r - 0.5 * s_sigma * s_sigma) * s_t
        vol = s_sigma * math.sqrt(s_t)
        discount = math.exp(-r * s_t)
        s_totals = [0.0] * n
        s_common = 0.0
        s_common_sq = 0.0
        for _ in range(pairs):
            z = rng.gauss(0.0, 1.0)
            # The antithetic pair. Both are real draws from the same
            # distribution; using them together is what removes the chance that
            # this seed happens to lean high.
            for draw in (z, -z):
                exit_value = equity_value * math.exp(drift + vol * draw)
                before = s_totals[:]
                payoff(exit_value, s_totals)
                common = sum(s_totals[i] - before[i] for i in common_at) * discount
                s_common += common
                s_common_sq += common * common
        count = pairs * 2
        for i in range(n):
            totals[i] += prob * discount * s_totals[i] / count
        # This scenario's contribution to the estimator's variance. The two
        # draws in an antithetic pair are deliberately correlated, so counting
        # them as two independent samples overstates the error the pairing
        # actually leaves — the reported figure is conservative in that one
        # direction, which is the safe direction for a precision claim.
        s_mean = s_common / count
        s_variance = max(0.0, s_common_sq / count - s_mean * s_mean)
        estimator_variance += prob * prob * s_variance / count
        per_scenario.append(
            {
                "name": scenario["name"],
                "probability": round(prob, 6),
                "years_to_exit": round(s_t, 4),
                "volatility": round(s_sigma, 6),
                "common_per_share": round(s_common / count / common_shares, 6),
            }
        )

    common_value = sum(totals[i] for i in common_at)
    # Standard error of the *mean*, which is what the conclusion uses. Reported
    # per share, because that is the unit the reader is judging it in.
    standard_error = math.sqrt(estimator_variance) / common_shares

    by_class = {
        c["name"]: {
            "kind": c["kind"],
            "shares": c["shares"],
            "value": round(totals[i], 2),
            "per_share": round(totals[i] / c["shares"], 6),
        }
        for i, c in enumerate(classes)
    }

    return {
        "method": "monte_carlo",
        "paths": pairs * 2,
        "antithetic": True,
        # Reported so the run can be reproduced exactly. A concluded value
        # nobody can re-derive is not a conclusion.
        "seed": seed,
        "scenarios": per_scenario,
        "classes": by_class,
        "common_value": round(common_value, 2),
        "common_shares": common_shares,
        "common_per_share": round(common_value / common_shares, 6),
        # The precision of the estimate itself, in the same unit as the
        # conclusion. A simulated figure without one is a number pretending to
        # be exact.
        "standard_error_per_share": round(standard_error, 8),
    }


__all__ = [
    "DEFAULT_PATHS",
    "DEFAULT_SEED",
    "MAX_PATHS",
    "MAX_SCENARIOS",
    "allocate_monte_carlo",
]
