"""Simulation-based allocation of equity value across the cap table.

What it is for
--------------
The closed-form OPM (``waterfall.allocate_waterfall``) prices each class as a
sum of Black-Scholes call spreads. That is exact, and it is exact *because* two
things hold: the payoff is piecewise linear in terminal equity value, and
terminal equity value is a single lognormal. Where both hold, simulating is
strictly worse than the closed form — same answer, plus noise.

They stop holding when the exit is not one lognormal. A company with a credible
IPO case at five years and a credible trade-sale case at two does not have one
expected exit: it has two, with different horizons and different volatilities,
and the common stock's value depends on the *whole distribution* within each,
not just on its mean. PWERM answers that with point estimates per scenario —
one exit value, no uncertainty around it — and the hybrid method blends a PWERM
point estimate with an OPM by a weight somebody chose.

This module is the thing between them: discrete scenarios, each carrying its own
horizon and volatility, with the equity evolving lognormally *inside* each. It
reduces exactly to the OPM when there is one scenario, which is how it is
tested, and to something PWERM-shaped as the volatilities go to zero.

Reproducibility
---------------
A 409A that returns a different fair market value each time it is run is
indefensible — a reviewer re-running it must get the concluded figure back, and
so must the analyst defending it three years later in an audit. So the draw is
seeded, the seed defaults to a constant, the seed travels in the result, and the
sequence is generated by this module's own PRNG instance rather than the global
one, which anything else in the process could have advanced.

Precision, and what it is not
-----------------------------
The estimator reports its own standard error, because a simulated figure without
one is a number pretending to be exact — and it reports a 95% confidence
interval, because a standard error is only useful to a reader who converts it.

This block used to claim that `paths` was "chosen so that error is small
relative to the rounding on a per-share conclusion" — that the default put the
standard error an order of magnitude below the fourth decimal the per-share
figure is stated to. That was wrong, and not by a little. On a mid-stage cap
table at sigma 0.6 and a four-year horizon, the default returns a per-share
value near $3.83 with a standard error near $0.054: 1.4% of the conclusion, and
some 500x the last digit printed beside it.

Nor is it reachable by simulating harder. The error falls as 1/sqrt(n), so
reaching 1e-4 from there needs about 5.7 billion paths — roughly 29,000 times
`MAX_PATHS`, which is itself a latency bound on a synchronous endpoint. The
honest statement is not that this method is precise to four decimals; it is that
it is precise to about one, that the interval says so, and that a reader
comparing two runs of it should compare the intervals rather than the digits.

That is a fact about simulation, not a defect in this module: the closed-form
OPM is exact and is what any single-lognormal engagement should use. What this
method buys is a payoff structure the closed form cannot price, and it is bought
at the cost of the last three decimals.

Conservation, and the regime where it fails
-------------------------------------------
The one thing this method is not entitled to get wrong is the total. Every
segment slope sums to one and the segments partition the exit value, so one
path allocates that path's exit value exactly, and the risk-neutral,
discounted mean of the exit value is the equity value being split. `Sigma class
values == equity_value` is therefore an identity in expectation, and the
residual measures only how well the draw sampled its own distribution.

It samples it badly much earlier than the volatility band suggests. The
terminal lognormal's mean lives in a right tail whose weight grows as
`exp(sigma^2 t)`, so the estimator needs paths in proportion. At the default
count a 100% volatility over seven years — inside `validate.VOLATILITY_BAND`,
with an unremarkable horizon — allocated 113% of the equity value, and the
reported standard error, struck from the same starved draw, said nothing. Past
`sigma sqrt(t)` of about 2 the residual runs to tens of percent, and at a
volatility of 5 every exit value underflows to zero and the whole cap table is
allocated nothing at all, reported as `$0.0000 per share` with a zero standard
error and a `[0, 0]` interval.

So the residual is measured, disclosed on every response as
`value_conservation`, and refused past `MAX_CONSERVATION_ERROR`. The closed-form
OPM has no such regime — it is exact at any volatility — which is what the
refusal points at.

Variance reduction
------------------
Antithetic variates: each normal draw Z is used with −Z as well. The payoff is
monotone in the draw, so the pair is negatively correlated and the mean of the
pair has materially lower variance than two independent draws. It costs one
extra waterfall evaluation and no extra randomness, and it makes the estimate
symmetric in the draw — a property worth having on its own, since it removes the
chance that a particular seed leans high or low overall.
"""

from __future__ import annotations

import math
import random

from .errors import EngineInputError
from .waterfall import _normalize, _segments

#: Simulated paths when the caller does not say — 10,000 antithetic pairs.
#:
#: A latency budget, not a precision target. The precision it buys is stated by
#: the interval the result carries and is roughly the first decimal of a
#: per-share figure; see "Precision, and what it is not" above for why no
#: reachable path count changes that. Chosen instead as the largest count that
#: keeps this synchronous endpoint inside a second on the cap tables this
#: platform sees. Fewer is defensible for exploration.
DEFAULT_PATHS = 20_000

#: Ceiling on one request. The inner loop is O(paths x segments x classes) in
#: pure Python and this endpoint is synchronous, so the bound is a latency bound
#: rather than a modelling one.
MAX_PATHS = 200_000

#: The seed a valuation uses unless one is recorded on it. Any constant would
#: do; what matters is that it is *a* constant and that it is reported.
DEFAULT_SEED = 409

#: Most scenarios anyone has a defensible story for.
MAX_SCENARIOS = 20

#: How far the allocated total may sit from the equity value before the run is
#: refused rather than reported.
#:
#: The module's whole claim to correctness is that the probability-weighted,
#: discounted payoff sums back to `equity_value` — the docstring says so, the
#: single-scenario case is checked against the closed form on it, and the
#: response tabulates a class-by-class split that a reader adds up. The sum is
#: also, per path, exactly `exp(-r t) x equity_value x exp(drift + vol z)`,
#: whose risk-neutral mean *is* the equity value, so the residual measures
#: nothing but how badly the draw sampled the distribution it was given.
#:
#: It sampled it badly far earlier than anyone would guess. The terminal
#: lognormal's mean is carried by its right tail, and the tail's weight grows as
#: `exp(sigma^2 t)`, so at 20,000 paths a 100% volatility over a seven-year
#: horizon — both inside `validate.VOLATILITY_BAND`, neither warned about —
#: allocated $11.3M of a $10.0M equity value, and 120% over five years allocated
#: $11.5M. Nothing said so: the classes summed to 113% of the value being
#: split, the per-share conclusion was 13% high, and `standard_error_per_share`
#: was struck from the same starved draw and so reported an interval as narrow
#: as if the figure were sound.
#:
#: Past this bound the failure is total rather than noisy. `sigma` of 5 over
#: four years underflows every exit value to zero, so the whole cap table is
#: allocated $0.00 and the conclusion comes back `$0.0000 per share` with a
#: standard error of exactly zero and a confidence interval of `[0, 0]` — a
#: figure claiming certainty about a value the closed form puts at the entire
#: equity. That is the shape R238 and R214 both found elsewhere: a boundary
#: answered with a finite, plausible, precise, wrong number.
#:
#: Set where it is because a low path count is a documented exploration mode
#: ("Fewer is defensible for exploration") and a coarse run is *supposed* to be
#: loose. A tenth of the equity value going somewhere the classes do not report
#: is past loose: it is larger than any discount this engine applies, larger
#: than the spread between two credible enterprise values, and it lands whole
#: on the per-share conclusion. Tightening it further starts refusing runs the
#: engine's own tests make on purpose at a few hundred paths, which is the
#: signal that the band below it is noise rather than failure — so that band is
#: reported instead, on `value_conservation`.
MAX_CONSERVATION_ERROR = 0.10

#: Two-sided 95% normal quantile, for the interval around the simulated mean.
NORMAL_95 = 1.959964


def _num(value, name: str, *, positive: bool = False, nonneg: bool = False) -> float | None:
    if value is None:
        return None
    try:
        out = float(value)
    except (TypeError, ValueError):
        raise EngineInputError(f"{name} must be a number") from None
    if not math.isfinite(out):
        raise EngineInputError(f"{name} must be finite")
    if positive and out <= 0:
        raise EngineInputError(f"{name} must be positive")
    if nonneg and out < 0:
        raise EngineInputError(f"{name} must be >= 0")
    return out


def _resolve_scenarios(raw, *, t: float, sigma: float) -> list[dict]:
    """Scenario list, defaulted to the single lognormal the OPM assumes.

    An absent or empty list is not an error: it is the ordinary case, and the
    single scenario it produces is what makes this method reduce to the OPM.
    """
    if raw is None:
        return [{"name": "Base", "probability": 1.0, "t": t, "sigma": sigma}]
    if not isinstance(raw, list) or not raw:
        raise EngineInputError("monte_carlo.scenarios must be a non-empty list when provided")
    if len(raw) > MAX_SCENARIOS:
        raise EngineInputError(f"monte_carlo.scenarios accepts at most {MAX_SCENARIOS} scenarios")

    out: list[dict] = []
    for i, entry in enumerate(raw):
        if not isinstance(entry, dict):
            raise EngineInputError(f"monte_carlo.scenarios[{i}] must be an object")
        prob = _num(entry.get("probability"), f"scenarios[{i}].probability", nonneg=True)
        if prob is None:
            raise EngineInputError(f"monte_carlo.scenarios[{i}].probability is required")
        # Each scenario may override the horizon and the volatility; a trade
        # sale in two years is not the same distribution as an IPO in five, and
        # collapsing them onto one pair of assumptions is exactly what this
        # method exists to avoid.
        out.append(
            {
                "name": str(entry.get("name") or f"Scenario {i + 1}"),
                "probability": prob,
                "t": _num(entry.get("years_to_exit"), f"scenarios[{i}].years_to_exit", positive=True) or t,
                "sigma": _num(entry.get("volatility"), f"scenarios[{i}].volatility", positive=True) or sigma,
            }
        )

    # Refused, not rescaled — and the comment this replaces had it backwards.
    #
    # It claimed that a set summing to 0.999 was a spreadsheet artefact rather
    # than a modelling error and that "`pwerm` already takes the same view of
    # the same input". `pwerm.allocate_pwerm` takes the opposite view: it
    # refuses any total more than 1e-6 from 1.0, and the pre-flight tells the
    # analyst in writing that "the engine weights each exit by its own
    # probability and does not rescale them".
    #
    # So the same three scenarios — an IPO, a trade sale and a wind-down at
    # 0.4 / 0.4 / 0.1, one digit short of a hundred percent — were a 422 naming
    # the field under PWERM and a silently reweighted 200 under Monte Carlo,
    # which is the one input both methods read identically and the one thing a
    # reader comparing two allocations of the same scenario set would assume.
    # Rescaling is also the worse half of the disagreement: the tenth of the
    # probability mass the analyst meant to put somewhere is not dropped, it is
    # redistributed across the scenarios they did type, and the run concludes on
    # weights nobody chose. The `scenarios[].probability` rows disclosed the
    # rescaled figures, so the only trace of it was a table of probabilities
    # that no longer matched the model the analyst had entered.
    total = sum(s["probability"] for s in out)
    if abs(total - 1.0) > 1e-6:
        raise EngineInputError(
            f"monte_carlo scenario probabilities must sum to 1.0 (got {total:.4f})"
        )
    return out


def _common_payoff_factory(classes: list[dict]):
    """A fast evaluator of every class's payoff at a given exit value.

    The breakpoint segments are built once and reused for every path. Building
    them per path — which calling ``exit_allocation`` in the loop would do —
    is the difference between a simulation that runs in a second and one that
    does not finish inside a request.

    Returned as flat parallel lists rather than the dicts ``_segments``
    produces, because this runs tens of thousands of times and attribute and
    hash lookups dominate at that count.
    """
    segments = _segments(classes)
    index = {c["name"]: i for i, c in enumerate(classes)}
    lows = [seg["from"] for seg in segments]
    # `None` (unbounded) becomes infinity, so the inner loop has no branch.
    highs = [math.inf if seg["to"] is None else seg["to"] for seg in segments]
    slopes = [[(index[name], frac) for name, frac in seg["participants"].items()] for seg in segments]

    def payoff(exit_value: float, into: list[float]) -> None:
        """Adds each class's share of `exit_value` into `into`, in place."""
        for lo, hi, participants in zip(lows, highs, slopes):
            if exit_value <= lo:
                # Segments are ordered, so nothing above this one is reached
                # either — the exit value ran out inside the previous tranche.
                break
            width = min(exit_value, hi) - lo
            for i, fraction in participants:
                into[i] += width * fraction

    return payoff


def allocate_monte_carlo(
    equity_value: float,
    inputs: dict,
    *,
    t: float,
    r: float,
    sigma: float,
) -> dict:
    """Allocate `equity_value` across the cap table by simulation.

    Risk-neutral, like the OPM it generalises: the equity value drifts at the
    risk-free rate and each scenario's payoff is discounted back at the same
    rate. That is what makes value conserve — the probability-weighted, present
    value of every class's payoff sums to `equity_value` — and it is what lets
    the single-scenario case be checked against the closed form.
    """
    if equity_value <= 0:
        raise EngineInputError("equity_value must be positive for the Monte Carlo allocation")
    raw_classes = inputs.get("share_classes")
    if not isinstance(raw_classes, list) or not raw_classes:
        raise EngineInputError(
            "allocation_method 'monte_carlo' requires inputs.share_classes (the cap table) — "
            "simulating a payoff needs the payoff structure it is simulating"
        )
    classes = _normalize(raw_classes)

    config = inputs.get("monte_carlo")
    if config is not None and not isinstance(config, dict):
        raise EngineInputError("inputs.monte_carlo must be an object")
    config = config or {}

    paths = int(_num(config.get("paths"), "monte_carlo.paths", positive=True) or DEFAULT_PATHS)
    if paths > MAX_PATHS:
        raise EngineInputError(f"monte_carlo.paths accepts at most {MAX_PATHS}")
    # Antithetic pairs, so the count is even by construction and the reported
    # figure is what was actually run rather than what was asked for.
    pairs = max(1, paths // 2)
    # `_num(...) or DEFAULT_SEED` would quietly turn a seed of 0 into 409 and
    # run a stream the analyst did not choose — the same defect `_normalize`
    # documents for a `conversion_ratio` of 0, and zero is an ordinary seed. The
    # run stayed reproducible, since the seed it reported was the one it used,
    # but an engagement pinned to seed 0 here and re-derived under seed 0
    # anywhere else would not have reconciled, and nothing on the page would
    # have said why. Only an absent seed defaults.
    raw_seed = _num(config.get("seed"), "monte_carlo.seed")
    seed = DEFAULT_SEED if raw_seed is None else int(raw_seed)
    scenarios = _resolve_scenarios(config.get("scenarios"), t=t, sigma=sigma)

    payoff = _common_payoff_factory(classes)
    n = len(classes)
    common_at = [i for i, c in enumerate(classes) if c["kind"] == "common"]
    common_shares = sum(c["shares"] for c in classes if c["kind"] == "common")
    if common_shares <= 0:  # pragma: no cover - `_normalize` already refuses both ways in
        # Kept as a divide-by-zero backstop for `common_per_share`, but not
        # reachable: `_normalize` requires at least one class of kind "common"
        # and requires every class's `shares` to be positive, so the sum here
        # cannot be zero. Both refusals are pinned in
        # `test_monte_carlo_precision.TestTheCapTableItNeeds`.
        raise EngineInputError("share_classes must include at least one common class with shares")

    rng = random.Random(seed)
    totals = [0.0] * n
    # Precision of the *common* payoff only — it is the figure the conclusion
    # rests on, and the one whose precision a reviewer asks about.
    #
    # Accumulated per scenario rather than into one pooled pair of moments,
    # because the scenarios are not draws from a common distribution: each has
    # its own horizon, volatility and weight. The estimator is
    # `Σ pᵢ·mean(scenario i)`, and the scenarios are drawn independently, so its
    # variance is `Σ pᵢ²·Var(mean(scenario i))` — a sum of per-scenario terms
    # that no pooled moment can be unwound into.
    #
    # Pooling them got both halves of `Var = E[c²] − E[c]²` wrong, and by
    # different factors: weighting each draw by `pᵢ` and then dividing by the
    # count of *all* draws made the reported mean `1/len(scenarios)` of the true
    # probability-weighted mean, so the subtracted term was off by that squared.
    # The residue was large and positive — two identical scenarios, which are by
    # construction the same distribution as one, reported a standard error that
    # did not fall as `1/√n`, and a deterministic payoff (σ→0) reported a
    # substantial error around a figure that was exact. Single-scenario runs
    # were unaffected, which is why the closed-form oracle never caught it.
    estimator_variance = 0.0
    per_scenario: list[dict] = []

    for scenario in scenarios:
        s_t, s_sigma, prob = scenario["t"], scenario["sigma"], scenario["probability"]
        drift = (r - 0.5 * s_sigma * s_sigma) * s_t
        vol = s_sigma * math.sqrt(s_t)
        discount = math.exp(-r * s_t)
        s_totals = [0.0] * n
        s_common = 0.0
        s_common_sq = 0.0
        for _ in range(pairs):
            z = rng.gauss(0.0, 1.0)
            # The antithetic pair. Both are real draws from the same
            # distribution; using them together is what removes the chance that
            # this seed happens to lean high.
            for draw in (z, -z):
                exit_value = equity_value * math.exp(drift + vol * draw)
                before = s_totals[:]
                payoff(exit_value, s_totals)
                common = sum(s_totals[i] - before[i] for i in common_at) * discount
                s_common += common
                s_common_sq += common * common
        count = pairs * 2
        for i in range(n):
            totals[i] += prob * discount * s_totals[i] / count
        # This scenario's contribution to the estimator's variance. The two
        # draws in an antithetic pair are deliberately correlated, so counting
        # them as two independent samples overstates the error the pairing
        # actually leaves — the reported figure is conservative in that one
        # direction, which is the safe direction for a precision claim.
        s_mean = s_common / count
        s_variance = max(0.0, s_common_sq / count - s_mean * s_mean)
        estimator_variance += prob * prob * s_variance / count
        per_scenario.append(
            {
                "name": scenario["name"],
                "probability": round(prob, 6),
                "years_to_exit": round(s_t, 4),
                "volatility": round(s_sigma, 6),
                "common_per_share": round(s_common / count / common_shares, 6),
            }
        )

    # The invariant, measured. Every segment slope sums to one and the segments
    # partition [0, inf), so one path's payoff over all classes is that path's
    # exit value exactly; probability-weighted and discounted, its mean is the
    # equity value. Anything left over is sampling error in the one figure this
    # method is not entitled to get wrong, and it is the only diagnostic that
    # sees the tail-starvation regime — `standard_error_per_share` is struck
    # from the same starved draw and shrinks right along with it.
    allocated_total = sum(totals)
    conservation_error = (allocated_total - equity_value) / equity_value
    if abs(conservation_error) > MAX_CONSERVATION_ERROR:
        raise EngineInputError(
            f"the Monte Carlo allocation did not conserve value: the classes were allocated "
            f"{allocated_total:,.2f} against an equity value of {equity_value:,.2f} "
            f"({conservation_error:+.1%}). The terminal distribution's mean sits in a tail this "
            f"draw did not reach — raise monte_carlo.paths (up to {MAX_PATHS}), shorten the "
            "horizon or lower the volatility, or use the 'opm' allocation, which prices the same "
            "payoff in closed form and is exact at any volatility"
        )

    common_value = sum(totals[i] for i in common_at)
    # Standard error of the *mean*, which is what the conclusion uses. Reported
    # per share, because that is the unit the reader is judging it in.
    standard_error = math.sqrt(estimator_variance) / common_shares
    common_per_share = common_value / common_shares
    # The interval, not just the error. Six decimals of per-share value sat
    # beside a standard error the reader had to double, sign and add themselves
    # before the figure meant anything — and on the default path count that
    # arithmetic moves the first decimal, so nobody skipping it could tell how
    # much of what they were reading was signal.
    #
    # The estimator is a probability-weighted sum of per-scenario means over
    # tens of thousands of draws, so it is normal by the central limit theorem
    # whatever the payoff's own distribution does, and the normal quantile is
    # the right one.
    half_width = NORMAL_95 * standard_error

    by_class = {
        c["name"]: {
            "kind": c["kind"],
            "shares": c["shares"],
            "value": round(totals[i], 2),
            "per_share": round(totals[i] / c["shares"], 6),
        }
        for i, c in enumerate(classes)
    }

    return {
        "method": "monte_carlo",
        "paths": pairs * 2,
        "antithetic": True,
        # Reported so the run can be reproduced exactly. A concluded value
        # nobody can re-derive is not a conclusion.
        "seed": seed,
        "scenarios": per_scenario,
        "classes": by_class,
        "common_value": round(common_value, 2),
        "common_shares": common_shares,
        # Exact — see `waterfall.allocate_waterfall`. The interval below and
        # the per-scenario figures above are read and not computed on, so
        # they keep the schedule's six places.
        "common_per_share": common_per_share,
        # The precision of the estimate itself, in the same unit as the
        # conclusion. A simulated figure without one is a number pretending to
        # be exact.
        "standard_error_per_share": round(standard_error, 8),
        # And the same precision as an interval, which is the form a reader
        # judges a figure in. Floored at zero: the payoff is a call spread and
        # cannot be negative, so an interval reaching below zero would be
        # reporting a value the model cannot produce.
        "common_per_share_ci95": [
            round(max(0.0, common_per_share - half_width), 6),
            round(common_per_share + half_width, 6),
        ],
        "confidence_level": 0.95,
        # What the classes above actually add up to, beside what they were
        # splitting. Disclosed on every run and not only on the refused ones,
        # because between "exact" and "refused" there is a wide band where the
        # allocation is usable and several percent loose, and a reader
        # reconciling an exhibit's class values against the equity value is
        # owed the difference rather than left to find it.
        "value_conservation": {
            "equity_value": round(equity_value, 2),
            "allocated_total": round(allocated_total, 2),
            "relative_error": round(conservation_error, 8),
            "tolerance": MAX_CONSERVATION_ERROR,
        },
    }


__all__ = [
    "DEFAULT_PATHS",
    "DEFAULT_SEED",
    "MAX_CONSERVATION_ERROR",
    "MAX_PATHS",
    "MAX_SCENARIOS",
    "NORMAL_95",
    "allocate_monte_carlo",
]
