import { useEffect, useState } from 'react';
import { ErrorNote, Spinner } from '../components/ui';

/**
 * Improvement 6 — partner API reference. The content is generated by the
 * server from the same registry the routes are registered from
 * (GET /api/partner/v1/docs), so this page can never drift from the API.
 */

interface EndpointDoc {
  method: 'GET' | 'POST';
  path: string;
  summary: string;
  auth: 'api_key' | 'none';
  body?: Record<string, string>;
  query?: Record<string, string>;
  response: string;
}

interface ApiDocs {
  name: string;
  version: string;
  base_url: string;
  authentication: { scheme: string; header: string; note: string };
  rate_limit: { limit: number; window_seconds: number; headers: string[] };
  endpoints: EndpointDoc[];
  /** Where the OpenAPI 3.1 document lives. Absent on older deployments. */
  openapi_url?: string;
}

function MethodChip({ method }: { method: EndpointDoc['method'] }) {
  const tone = method === 'GET' ? 'bg-bond-50 text-bond-700' : 'bg-emerald-50 text-emerald-700';
  return <span className={`tnum rounded px-1.5 py-0.5 font-mono text-xs font-bold ${tone}`}>{method}</span>;
}

function FieldTable({ title, fields }: { title: string; fields: Record<string, string> }) {
  return (
    <div className="mt-3">
      <div className="overline text-xs text-ink-400">{title}</div>
      <table className="mt-1 w-full text-sm">
        <tbody>
          {Object.entries(fields).map(([name, desc]) => (
            <tr key={name} className="border-b border-paper-200 last:border-0">
              <td className="w-44 py-1.5 pr-4 align-top font-mono text-xs font-semibold text-ink-800">
                {name}
              </td>
              <td className="py-1.5 text-ink-600">{desc}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function ApiDocsPage() {
  const [docs, setDocs] = useState<ApiDocs | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/partner/v1/docs', { headers: { accept: 'application/json' } })
      .then((res) => {
        if (!res.ok) throw new Error(String(res.status));
        return res.json() as Promise<ApiDocs>;
      })
      .then(setDocs)
      .catch(() => setError('Could not load the API reference.'));
  }, []);

  return (
    <div className="max-w-3xl">
      <div className="overline text-ink-400">Partner API</div>
      <h1 className="mt-1 font-display text-3xl font-semibold text-ink-900">API reference</h1>
      <p className="mt-1 text-sm text-ink-400">
        Programmatic valuation submission — create engagements, upload documents, poll status, and retrieve
        results from your own systems.
      </p>

      {error && (
        <div className="mt-6">
          <ErrorNote>{error}</ErrorNote>
        </div>
      )}
      {!docs && !error && <Spinner />}

      {docs && (
        <>
          {/*
            * The spec, first and above the prose. A partner's first move is to
            * generate a client, not to read fourteen endpoint cards — and a
            * reference that buries the machine-readable version at the bottom
            * gets hand-written HTTP clients built against it instead.
            */}
          {docs.openapi_url && (
            <section className="mt-8 rounded-lg border border-bond-200 bg-bond-50 p-5">
              <h2 className="overline mb-1.5 text-ink-500">Machine-readable spec</h2>
              <p className="text-sm text-ink-700">
                Everything below is also published as an{' '}
                <a
                  href={docs.openapi_url}
                  className="font-semibold text-bond-700 underline underline-offset-2 hover:text-bond-800"
                >
                  OpenAPI 3.1 document
                </a>
                . Import it into Postman or Insomnia, or point a client generator at it:
              </p>
              <pre className="mt-3 overflow-x-auto rounded bg-ink-900 px-3.5 py-2.5 font-mono text-xs text-paper-50">
                <code>{`npx @openapitools/openapi-generator-cli generate \\\n  -i ${docs.openapi_url} -g typescript-fetch -o ./n409-client`}</code>
              </pre>
            </section>
          )}

          <section className="mt-8 rounded-lg border border-paper-300 bg-surface p-6 shadow-card">
            <h2 className="overline mb-2 text-ink-400">Authentication</h2>
            <p className="text-sm text-ink-600">
              Send an API key with every request:{' '}
              <code className="rounded bg-paper-200 px-1 py-0.5 font-mono text-xs">
                {docs.authentication.header}
              </code>
            </p>
            <p className="mt-2 text-sm text-ink-400">{docs.authentication.note}</p>
            <h2 className="overline mt-6 mb-2 text-ink-400">Rate limits</h2>
            <p className="text-sm text-ink-600">
              <span className="tnum font-semibold">{docs.rate_limit.limit}</span> requests per{' '}
              <span className="tnum font-semibold">{docs.rate_limit.window_seconds}s</span> per API key.
              Current usage is returned in{' '}
              {docs.rate_limit.headers.map((h, i) => (
                <span key={h}>
                  {i > 0 && ', '}
                  <code className="rounded bg-paper-200 px-1 py-0.5 font-mono text-xs">{h}</code>
                </span>
              ))}
              .
            </p>
          </section>

          <div className="mt-8 space-y-4">
            {docs.endpoints.map((ep) => (
              <section
                key={`${ep.method} ${ep.path}`}
                className="rounded-lg border border-paper-300 bg-surface p-5 shadow-card"
              >
                <div className="flex flex-wrap items-center gap-2">
                  <MethodChip method={ep.method} />
                  <code className="break-all font-mono text-sm font-semibold text-ink-900">
                    {docs.base_url}
                    {ep.path}
                  </code>
                  {ep.auth === 'none' && (
                    <span className="rounded bg-paper-200 px-1.5 py-0.5 text-xs text-ink-500">no auth</span>
                  )}
                </div>
                <p className="mt-2 text-sm text-ink-600">{ep.summary}</p>
                {ep.body && <FieldTable title="Body" fields={ep.body} />}
                {ep.query && <FieldTable title="Query" fields={ep.query} />}
                <div className="mt-3 text-xs text-ink-400">
                  Response: <span className="font-mono">{ep.response}</span>
                </div>
              </section>
            ))}
          </div>
        </>
      )}
    </div>
  );
}
