import { useId, useEffect, useState } from 'react';
import { ErrorNote, Spinner } from './ui';

/**
 * The live partner API reference.
 *
 * Generated by the server from the same registry the routes are registered
 * from (GET /api/partner/v1/docs), so it can never drift from the API. The
 * endpoint needs no authentication, which is what lets the same component
 * serve the signed-in partner console at /partner/api-docs and the public
 * developer page at /developers.
 *
 * It fetches, so it renders nothing useful in a prerender. Anything a crawler
 * has to read belongs in the page around it, not in here.
 */

interface EndpointDoc {
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  path: string;
  summary: string;
  auth: 'api_key' | 'none';
  body?: Record<string, string>;
  query?: Record<string, string>;
  response: string;
}

interface ApiDocs {
  name: string;
  version: string;
  base_url: string;
  authentication: { scheme: string; header: string; note: string };
  rate_limit: { limit: number; window_seconds: number; headers: string[] };
  endpoints: EndpointDoc[];
  /** Where the OpenAPI 3.1 document lives. Absent on older deployments. */
  openapi_url?: string;
}

/**
 * The verb, coloured by what it does to the resource.
 *
 * This typed `method` as `'GET' | 'POST'` while the registry had been serving
 * three DELETE endpoints for some time, so the reference painted "revoke this
 * webhook" in the same green as "create a valuation" — and TypeScript could not
 * say so, because the type was a claim about the server rather than a reading
 * of it. Read-only, creates, replaces and deletes are four different promises
 * to somebody scanning the page for the one that will remove their data.
 */
const METHOD_TONES: Record<EndpointDoc['method'], string> = {
  GET: 'bg-bond-50 text-bond-700',
  POST: 'bg-emerald-50 text-emerald-700',
  PUT: 'bg-amber-50 text-amber-700',
  // `red`, and deliberately not the neighbouring family one step around the
  // wheel. Dark mode here is one block of re-pointed palette steps rather than
  // a set of `dark:` variants, and that block has never carried that family —
  // so the lightest step of it stays near-white under a dark theme, which would
  // have put a glaring chip on a dark table on the one verb that removes a
  // partner's data. Same substitution the Stripe test-mode warning and the
  // research badge made, and `themeTokens.test.ts` is what caught it.
  DELETE: 'bg-red-50 text-red-700',
};

function MethodChip({ method }: { method: EndpointDoc['method'] }) {
  const tone = METHOD_TONES[method] ?? METHOD_TONES.POST;
  return <span className={`tnum rounded px-1.5 py-0.5 font-mono text-xs font-bold ${tone}`}>{method}</span>;
}

function FieldTable({ title, fields }: { title: string; fields: Record<string, string> }) {
  const titleId = useId();
  return (
    <div className="mt-3">
      <div id={titleId} className="overline text-xs text-ink-400">
        {title}
      </div>
      <table className="mt-1 w-full text-sm" aria-labelledby={titleId}>
        <tbody>
          {Object.entries(fields).map(([name, desc]) => (
            <tr key={name} className="border-b border-paper-200 last:border-0">
              <td className="w-44 py-1.5 pr-4 align-top font-mono text-xs font-semibold text-ink-800">
                {name}
              </td>
              <td className="py-1.5 text-ink-600">{desc}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function ApiReference() {
  const [docs, setDocs] = useState<ApiDocs | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/partner/v1/docs', { headers: { accept: 'application/json' } })
      .then((res) => {
        if (!res.ok) throw new Error(String(res.status));
        return res.json() as Promise<ApiDocs>;
      })
      .then(setDocs)
      .catch(() => setError('Could not load the API reference.'));
  }, []);

  return (
    <div>
      {error && (
        <div className="mt-6">
          <ErrorNote>{error}</ErrorNote>
        </div>
      )}
      {!docs && !error && <Spinner />}

      {docs && (
        <>
          {/*
           * The spec, first and above the prose. A partner's first move is to
           * generate a client, not to read fourteen endpoint cards — and a
           * reference that buries the machine-readable version at the bottom
           * gets hand-written HTTP clients built against it instead.
           */}
          {docs.openapi_url && (
            <section className="mt-8 rounded-lg border border-bond-200 bg-bond-50 p-5">
              <h2 className="overline mb-1.5 text-ink-500">Machine-readable spec</h2>
              <p className="text-sm text-ink-700">
                Everything below is also published as an{' '}
                <a
                  href={docs.openapi_url}
                  className="font-semibold text-bond-700 underline underline-offset-2 hover:text-bond-800"
                >
                  OpenAPI 3.1 document
                </a>
                . Import it into Postman or Insomnia, or point a client generator at it:
              </p>
              <pre className="mt-3 overflow-x-auto rounded bg-ink-900 px-3.5 py-2.5 font-mono text-xs text-paper-50">
                <code>{`npx @openapitools/openapi-generator-cli generate \\\n  -i ${docs.openapi_url} -g typescript-fetch -o ./n409-client`}</code>
              </pre>
            </section>
          )}

          <section className="mt-8 rounded-lg border border-paper-300 bg-surface p-6 shadow-card">
            <h2 className="overline mb-2 text-ink-400">Authentication</h2>
            <p className="text-sm text-ink-600">
              Send an API key with every request:{' '}
              <code className="rounded bg-paper-200 px-1 py-0.5 font-mono text-xs">
                {docs.authentication.header}
              </code>
            </p>
            <p className="mt-2 text-sm text-ink-400">{docs.authentication.note}</p>
            <h2 className="overline mt-6 mb-2 text-ink-400">Rate limits</h2>
            <p className="text-sm text-ink-600">
              <span className="tnum font-semibold">{docs.rate_limit.limit}</span> requests per{' '}
              <span className="tnum font-semibold">{docs.rate_limit.window_seconds}s</span> per API key.
              Current usage is returned in{' '}
              {docs.rate_limit.headers.map((h, i) => (
                <span key={h}>
                  {i > 0 && ', '}
                  <code className="rounded bg-paper-200 px-1 py-0.5 font-mono text-xs">{h}</code>
                </span>
              ))}
              .
            </p>
          </section>

          <div className="mt-8 space-y-4">
            {docs.endpoints.map((ep) => (
              <section
                key={`${ep.method} ${ep.path}`}
                className="rounded-lg border border-paper-300 bg-surface p-5 shadow-card"
              >
                <div className="flex flex-wrap items-center gap-2">
                  <MethodChip method={ep.method} />
                  <code className="break-all font-mono text-sm font-semibold text-ink-900">
                    {docs.base_url}
                    {ep.path}
                  </code>
                  {ep.auth === 'none' && (
                    <span className="rounded bg-paper-200 px-1.5 py-0.5 text-xs text-ink-500">no auth</span>
                  )}
                </div>
                <p className="mt-2 text-sm text-ink-600">{ep.summary}</p>
                {ep.body && <FieldTable title="Body" fields={ep.body} />}
                {ep.query && <FieldTable title="Query" fields={ep.query} />}
                <div className="mt-3 text-xs text-ink-400">
                  Response: <span className="font-mono">{ep.response}</span>
                </div>
              </section>
            ))}
          </div>
        </>
      )}
    </div>
  );
}
