import { PROBLEM_CATALOG } from '@n409/shared';
import { SESSION_COOKIE } from '../auth/cookies.js';
import { operationId, pathParameters } from './openapi.js';

/**
 * OpenAPI 3.1 for the client/admin API, generated from the route table the
 * service actually registers.
 *
 * The partner API has had a spec since the round that built one from its
 * registry. The client API — 460-odd routes, everything the web app and the
 * firm workspace talk to — had nothing machine-readable at all. What stood in
 * for it was §2 of `docs/api-design.md`, which is a *design sketch* written
 * before the service existed: it lists paths without the `/api/v1` prefix they
 * ship under, names a handful of routes out of hundreds, and still describes an
 * AI provider that was removed. Nobody was misled by it for long, because
 * nobody could use it — but there was also nothing to import into a tool, no
 * way to answer "does this endpoint exist" without grepping, and no statement
 * anywhere of which routes are reachable without a session.
 *
 * ## What this document claims, and what it does not
 *
 * It is derived from `app.routeAudit`, so the *inventory* is exact and cannot
 * drift: every registered route appears, nothing that is not registered does,
 * and whether an operation requires a session is read from the preHandler
 * rather than from a list somebody maintains. The error half is equally real —
 * the responses come from `PROBLEM_CATALOG`, the same catalog the services
 * raise from and the published table renders from.
 *
 * What it does *not* claim is per-endpoint prose. There is no request or
 * response schema for these routes to derive one from: the client API validates
 * inside its handlers with zod rather than through fastify's `schema` option,
 * and a `summary` generated by rearranging the words already in the path would
 * be filler that reads like documentation. So prose lives at the tag level,
 * where it is written by hand and is true, and each operation carries what can
 * be stated exactly: its identifier, its tag, its path parameters, whether it
 * needs a session, and — for the unauthenticated ones — the reason from
 * `PUBLIC_ROUTES`, which is prose that already exists and is already reviewed.
 *
 * Writing that boundary down matters more than closing it. A spec that invents
 * a summary for every operation looks more complete and is less trustworthy,
 * because a reader cannot tell which sentences were written about the endpoint
 * and which were generated from its URL.
 *
 * The partner routes are excluded on purpose: they have a richer spec of their
 * own at `/api/partner/v1/openapi.json`, with request and response schemas, and
 * publishing a thinner second description of the same endpoints would give a
 * partner two documents to choose between. The section is still declared, so
 * the census below accounts for those routes rather than silently skipping
 * them.
 */

/** A group of endpoints, and what it is for. */
export interface ApiTag {
  name: string;
  description: string;
}

/**
 * Prose for each tag.
 *
 * This is the hand-written half of the document and the only place prose is
 * added. `apiCatalog.test.ts` requires every tag to be reached by at least one
 * section and every section by at least one route, so a tag cannot survive the
 * feature it described being deleted.
 */
export const API_TAGS: readonly ApiTag[] = [
  {
    name: 'Service',
    description:
      'Liveness, readiness and the Prometheus scrape. Unauthenticated by necessity — they are what a ' +
      'supervisor and a reverse proxy call — so `/ready` reports *whether* it is ready in the body and ' +
      'the reasons only to a caller holding the metrics token.',
  },
  {
    name: 'Authentication',
    description:
      'Sign-in, registration, password recovery, email verification, the second factor, and the two ' +
      'federated paths (Google OIDC and SAML). Every route here is public by construction — a route ' +
      'that mints a session cannot require one — and each is rate limited and validates its own ' +
      'credential.',
  },
  {
    name: 'Account security',
    description:
      "The signed-in user's own MFA enrolment: setup, confirmation, backup codes, and disabling it. " +
      'Separate from Authentication because these need a session; the challenge that spends the ' +
      'factor does not.',
  },
  {
    name: 'Current user',
    description:
      'Everything scoped to "me" rather than to an id — profile, capabilities, notification ' +
      'preferences, sessions, personal API tokens, the subscription and billing summary, and the ' +
      'Article 15 personal-data export.',
  },
  {
    name: 'User administration',
    description:
      'Managing other people: the user list and its export, invitations, role promotion and ' +
      'demotion, session revocation, password-reset dispatch, and the per-user data export an ' +
      'administrator runs on a subject’s behalf. Every write records an admin event.',
  },
  {
    name: 'Organisations',
    description:
      'The corporate group: parent organisations, their entities, and the consolidated roll-up. A ' +
      'subsidiary is only eliminated by a parent that is present in the roll-up, which is why the ' +
      'entity routes refuse a delete that would strand one.',
  },
  {
    name: 'Partners',
    description:
      'Partner firms as records the platform administers — their details, their saved view, their ' +
      'API tokens, and the valuations in their scope. Distinct from the Partner API, which is what ' +
      'those firms call.',
  },
  {
    name: 'Partner API',
    description:
      'Token-authenticated endpoints for partner firms. Documented separately and in far more detail ' +
      '— with request and response schemas — at `/api/partner/v1/openapi.json`, so the operations are ' +
      'deliberately not repeated here.',
  },
  {
    name: 'API tokens',
    description: 'Revoking an issued API token by id. Tokens are minted per partner or per user.',
  },
  {
    name: 'Firm workspace',
    description:
      'The valuation firm’s own view of its book: the dashboard, the client list, what needs ' +
      'attention, engagement records, and the intake links a firm sends a prospective client.',
  },
  {
    name: 'Valuations',
    description:
      'The engagement and everything hanging off it — inputs, cap table, documents, calculations, ' +
      'the report, the workbook, review and sign-off, and the specialty measurements. This is the ' +
      'largest surface on the API by a wide margin; the path after the valuation id names the ' +
      'sub-resource.',
  },
  {
    name: 'Valuation schemas',
    description:
      'The field dictionaries the workspace renders from: which overwrites exist, which intake ' +
      'questions apply to a kind, and which inputs each specialty engine takes. Static per release, ' +
      'so a client may cache them.',
  },
  {
    name: 'Cap table',
    description:
      'Cap-table concerns that are not scoped to one valuation — chiefly the import formats the ' +
      'spreadsheet parser accepts.',
  },
  {
    name: 'Fund measurement',
    description:
      'Fund-level NAV work: positions and their marks, LP terms and the distribution waterfall, ' +
      'calibration, and the roll-forward of a position between measurement dates.',
  },
  {
    name: 'Debt measurement',
    description:
      'Debt instruments and their fair value: credit terms, the rating-to-spread lookup, and the ' +
      'valuation history of an instrument.',
  },
  {
    name: 'Billing',
    description:
      'Plans, subscription, the Stripe customer portal, invoice PDFs, and the Stripe webhooks. The ' +
      'webhook routes are public because Stripe calls them; they authenticate on the signature.',
  },
  {
    name: 'Administration',
    description:
      'Operator surfaces: prompts and narrative prompts, communication templates, the email outbox ' +
      'and suppression list, scheduled jobs and their alert rules, retention policies and legal ' +
      'holds, webhook deliveries, SSO configuration, connection-pool and slow-query diagnostics, and ' +
      'the system settings. Ops roles only, and every write is audited.',
  },
  {
    name: 'Client intake',
    description:
      'The portal a client company uses to answer the questionnaire and hand over documents, plus the ' +
      'question schema behind it.',
  },
  {
    name: 'Auditor portal',
    description:
      'The read-only surface an external auditor is granted per engagement. Scoped by a grant with an ' +
      'expiry rather than by a role.',
  },
  {
    name: 'Board approval',
    description:
      'Board resolution generation and the signature capture that records approval of a concluded ' +
      'fair market value.',
  },
  {
    name: 'Integration callbacks',
    description:
      'OAuth returns from the accounting, HRIS and cap-table providers. Public because the provider ' +
      'redirects a browser to them, and authenticated by the signed `state` they carry.',
  },
  {
    name: 'Inbound webhooks',
    description:
      'Delivery and engagement events posted by the email provider. Authenticated on a shared secret, ' +
      'not a session.',
  },
  {
    name: 'Email preferences',
    description:
      'One-click unsubscribe (RFC 8058). Both verbs are public and authenticated by the signed, ' +
      'scoped, expiring token in the query string — the POST arrives from a mailbox provider with no ' +
      'user present.',
  },
  {
    name: 'Inbox and notifications',
    description:
      'In-app notifications and the shared inbox of inbound email: unread counts, marking read, and ' +
      'routing a message to an engagement.',
  },
  {
    name: 'Tasks and reviews',
    description: 'Work assignment across the firm — review queues and the task list they generate.',
  },
  {
    name: 'Comments',
    description: 'Editing and deleting a comment by id; the threads themselves hang off a valuation.',
  },
  {
    name: 'Search and views',
    description:
      'Cross-entity search, saved views, the tag catalogue, and the valuation selector the workspace ' +
      'uses to switch engagements.',
  },
  {
    name: 'Analytics',
    description: 'The dashboard pivot: counts by stage and product, and the bands behind the charts.',
  },
  {
    name: 'Monitoring',
    description:
      'Standing monitors that watch an engagement for a triggering event — a new round, a stale ' +
      'valuation — and raise it rather than waiting to be asked.',
  },
  {
    name: 'Onboarding',
    description:
      'Progress through the getting-started checklist on the dashboard. Derived from the caller’s own ' +
      'valuations rather than from a stored flag, so the checklist agrees with the rest of the screen.',
  },
  {
    name: 'Research',
    description:
      'The research topics the AI gateway can be asked to gather evidence on, independent of any one ' +
      'engagement.',
  },
  {
    name: 'FMV estimator',
    description:
      'The pre-engagement estimate: a rough fair-market value from a handful of inputs, used to price ' +
      'the work rather than to conclude it. Not a valuation opinion.',
  },
  {
    name: 'Templates',
    description:
      'Report templates and grant templates — the skeletons a new engagement or a new award is ' +
      'created from, with activation and archival.',
  },
  {
    name: 'Content',
    description: 'Marketing blog posts and the help knowledge base the in-app help widget reads.',
  },
  {
    name: 'Branding',
    description:
      'White-label chrome: the tenant’s logo, colours and domain. The pre-login half is under Public ' +
      'chrome, because a sign-in page has to render before there is a session.',
  },
  {
    name: 'Public chrome',
    description:
      'What an unauthenticated browser needs to render a sign-in page: branding resolved from the ' +
      'subdomain or partner key, and whether registration is open. Configuration, not data.',
  },
  {
    name: 'Support',
    description: 'The in-app support thread and the public contact form, plus its submission queue.',
  },
  {
    name: 'Sample report',
    description:
      'A complete 409A report rendered on a fictitious company, as the outline and as the PDF. Every ' +
      'page is marked as not a valuation opinion and no engagement data is reachable from it.',
  },
  {
    name: 'SCIM provisioning',
    description:
      'SCIM 2.0 user provisioning for enterprise directories. Authenticated with a SCIM token rather ' +
      'than a session.',
  },
  {
    name: 'API documentation',
    description:
      'This document and the error catalog it references — both public, because documentation behind ' +
      'a credential cannot help somebody whose credential is what is failing.',
  },
];

/**
 * A route prefix and the tag it belongs to.
 *
 * Matched longest-prefix-first, so `/api/v1/valuations/:id/payments` can belong
 * to Billing while everything else under `/api/v1/valuations` belongs to
 * Valuations. A prefix matches a path only at a segment boundary — `/api/v1/me`
 * does not swallow `/api/v1/metrics` — which is the bug this would otherwise
 * have shipped with, since the two differ after the shared prefix by a
 * character rather than by a slash.
 */
export interface ApiSection {
  prefix: string;
  tag: string;
  /** Declared but not rendered — see the Partner API note in the file docblock. */
  excluded?: true;
}

export const API_SECTIONS: readonly ApiSection[] = [
  { prefix: '/', tag: 'Service' },
  { prefix: '/health', tag: 'Service' },
  { prefix: '/ready', tag: 'Service' },
  { prefix: '/metrics', tag: 'Service' },
  { prefix: '/scim/v2', tag: 'SCIM provisioning' },
  { prefix: '/api/partner/v1', tag: 'Partner API', excluded: true },

  { prefix: '/api/v1/openapi.json', tag: 'API documentation' },
  { prefix: '/api/v1/problems', tag: 'API documentation' },

  { prefix: '/api/v1/auth', tag: 'Authentication' },
  { prefix: '/api/v1/account', tag: 'Account security' },
  { prefix: '/api/v1/me', tag: 'Current user' },
  { prefix: '/api/v1/users', tag: 'User administration' },
  { prefix: '/api/v1/roles', tag: 'User administration' },
  { prefix: '/api/v1/organizations', tag: 'Organisations' },
  { prefix: '/api/v1/partners', tag: 'Partners' },
  { prefix: '/api/v1/api-tokens', tag: 'API tokens' },

  { prefix: '/api/v1/firm', tag: 'Firm workspace' },
  { prefix: '/api/v1/engagements', tag: 'Firm workspace' },

  { prefix: '/api/v1/valuations', tag: 'Valuations' },
  { prefix: '/api/v1/valuations/:id/payments', tag: 'Billing' },
  { prefix: '/api/v1/overwrites', tag: 'Valuation schemas' },
  { prefix: '/api/v1/specialty', tag: 'Valuation schemas' },
  { prefix: '/api/v1/intake/schema', tag: 'Valuation schemas' },
  { prefix: '/api/v1/cap-table', tag: 'Cap table' },

  { prefix: '/api/v1/funds', tag: 'Fund measurement' },
  { prefix: '/api/v1/debt', tag: 'Debt measurement' },

  { prefix: '/api/v1/billing', tag: 'Billing' },
  { prefix: '/api/v1/stripe', tag: 'Billing' },

  { prefix: '/api/v1/admin', tag: 'Administration' },

  { prefix: '/api/v1/intake', tag: 'Client intake' },
  { prefix: '/api/v1/auditor', tag: 'Auditor portal' },
  { prefix: '/api/v1/board', tag: 'Board approval' },

  { prefix: '/api/v1/accounting', tag: 'Integration callbacks' },
  { prefix: '/api/v1/hris', tag: 'Integration callbacks' },
  { prefix: '/api/v1/cap-table-sync', tag: 'Integration callbacks' },
  { prefix: '/api/v1/webhooks', tag: 'Inbound webhooks' },
  { prefix: '/api/v1/unsubscribe', tag: 'Email preferences' },

  { prefix: '/api/v1/inbox', tag: 'Inbox and notifications' },
  { prefix: '/api/v1/notifications', tag: 'Inbox and notifications' },
  { prefix: '/api/v1/tasks', tag: 'Tasks and reviews' },
  { prefix: '/api/v1/reviews', tag: 'Tasks and reviews' },
  { prefix: '/api/v1/comments', tag: 'Comments' },

  { prefix: '/api/v1/search', tag: 'Search and views' },
  { prefix: '/api/v1/saved-views', tag: 'Search and views' },
  { prefix: '/api/v1/tag-catalogue', tag: 'Search and views' },
  { prefix: '/api/v1/valuation-selector', tag: 'Search and views' },

  { prefix: '/api/v1/stats', tag: 'Analytics' },
  { prefix: '/api/v1/monitors', tag: 'Monitoring' },
  { prefix: '/api/v1/onboarding', tag: 'Onboarding' },
  { prefix: '/api/v1/research', tag: 'Research' },
  { prefix: '/api/v1/fmv-estimator', tag: 'FMV estimator' },

  { prefix: '/api/v1/report-templates', tag: 'Templates' },
  { prefix: '/api/v1/grant-templates', tag: 'Templates' },
  { prefix: '/api/v1/blog', tag: 'Content' },
  { prefix: '/api/v1/help', tag: 'Content' },
  { prefix: '/api/v1/branding', tag: 'Branding' },
  { prefix: '/api/v1/public', tag: 'Public chrome' },
  { prefix: '/api/v1/support', tag: 'Support' },
  { prefix: '/api/v1/contact', tag: 'Support' },
  { prefix: '/api/v1/sample-report', tag: 'Sample report' },
];

/** Does `path` sit at or under `prefix`, at a segment boundary? */
export function underPrefix(path: string, prefix: string): boolean {
  if (prefix === '/') return path === '/';
  return path === prefix || path.startsWith(`${prefix}/`);
}

/**
 * The most specific section covering `path`, or undefined if none does — which
 * the census treats as a failure rather than as a default, so a new top-level
 * resource has to be placed rather than quietly landing in whatever tag sorts
 * first.
 */
export function sectionFor(path: string): ApiSection | undefined {
  let best: ApiSection | undefined;
  for (const section of API_SECTIONS) {
    if (!underPrefix(path, section.prefix)) continue;
    if (!best || section.prefix.length > best.prefix.length) best = section;
  }
  return best;
}

/** `METHOD /url` as the route audit spells it, split back into its halves. */
export function parseRouteKey(key: string): { method: string; path: string } {
  const cut = key.indexOf(' ');
  return { method: key.slice(0, cut), path: key.slice(cut + 1) };
}

/** `:id` → `{id}`, which is what OpenAPI templating wants. */
export function templatePath(path: string): string {
  return path.replace(/:([A-Za-z_][A-Za-z0-9_]*)/g, '{$1}');
}

const PROBLEM_REF = { $ref: '#/components/schemas/Problem' };

function problemResponse(type: string): Record<string, unknown> {
  const entry = PROBLEM_CATALOG[type];
  return {
    // Description straight from the catalog, so the spec's account of a failure
    // is the same sentence the published table gives and the same one the
    // `/api/v1/problems` endpoint serves. Three renderings, one source.
    description: entry ? `${entry.summary} ${entry.resolution}` : type,
    content: { 'application/problem+json': { schema: PROBLEM_REF } },
  };
}

/**
 * The problem document, as a component every operation references.
 *
 * Kept in step with the shared handler by `apiCatalog.test.ts`, which builds a
 * real `ApiProblem` body and checks every key it produces is declared here — a
 * spec that under-reports the error body is how a client ends up with no
 * generated type for `retry_after_seconds`, which is the one field a 429
 * handler needs.
 */
const PROBLEM_SCHEMA = {
  type: 'object',
  description:
    'RFC 9457 problem document. Every failure on this API uses this shape, served as ' +
    'application/problem+json. Branch on `type` — the vocabulary is at GET /api/v1/problems.',
  properties: {
    type: {
      type: 'string',
      description: 'Stable URN identifying the problem class. The only field to branch on.',
      enum: Object.keys(PROBLEM_CATALOG),
    },
    title: { type: 'string', description: 'Constant reason phrase for this type.' },
    status: { type: 'integer', description: 'HTTP status code, repeated in the body.' },
    detail: { type: 'string', description: 'Explanation specific to this occurrence. Absent on 5xx.' },
    instance: { type: 'string', description: 'The request path this failure occurred on.' },
    errors: {
      type: 'array',
      description: 'Field-level validation issues, present on 422 responses.',
      items: { type: 'object' },
    },
    retry_after_seconds: {
      type: 'integer',
      description: 'Seconds to wait before retrying. Mirrors the retry-after response header.',
    },
  },
  required: ['type', 'title', 'status'],
};

export interface ClientOpenApiInput {
  /** `METHOD /url` for every registered route — `app.routeAudit.all()`. */
  routes: readonly string[];
  /** The subset of those that run through `app.authenticate`. */
  authenticated: ReadonlySet<string>;
  /** Route key → why it is reachable without a session, from `PUBLIC_ROUTES`. */
  publicReasons: ReadonlyMap<string, string>;
  version: string;
}

/**
 * The generated document.
 *
 * Pure function of its input, so the route that serves it can rebuild per
 * request and never hold a stale copy — the same choice the partner spec makes,
 * and for the same reason.
 */
export function buildClientOpenApiDocument(input: ClientOpenApiInput): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {};
  const usedTags = new Set<string>();

  for (const key of input.routes) {
    const { method, path } = parseRouteKey(key);
    const section = sectionFor(path);
    if (!section || section.excluded) continue;
    usedTags.add(section.tag);

    const authenticated = input.authenticated.has(key);
    const reason = input.publicReasons.get(key);
    const parameters = pathParameters(templatePath(path)).map((name) => ({
      name,
      in: 'path',
      required: true,
      schema: { type: 'string' },
      description: `Identifier from a previous response (${name}).`,
    }));

    const operation: Record<string, unknown> = {
      operationId: operationId(method, templatePath(path)),
      tags: [section.tag],
      ...(parameters.length > 0 ? { parameters } : {}),
      // Only for the public routes, where `PUBLIC_ROUTES` already carries a
      // reviewed sentence about why no session is needed. Everywhere else the
      // operation says nothing rather than saying something generated.
      ...(reason ? { description: `Reachable without a session: ${reason}.` } : {}),
      responses: {
        '2XX': { description: 'Success. Response bodies are not described by this document.' },
        ...(authenticated
          ? {
              '401': problemResponse('urn:n409:problem:unauthorized'),
              '403': problemResponse('urn:n409:problem:forbidden'),
            }
          : {}),
        '404': problemResponse('urn:n409:problem:not-found'),
        '422': problemResponse('urn:n409:problem:validation'),
        '429': problemResponse('urn:n409:problem:rate-limited'),
        '500': problemResponse('urn:n409:problem:internal'),
      },
      // `security: []` is not the same as omitting the key: it explicitly clears
      // the document-level requirement, which is how a public route is marked.
      security: authenticated ? [{ session: [] }, { bearer: [] }] : [],
    };

    const templated = templatePath(path);
    paths[templated] ??= {};
    paths[templated]![method.toLowerCase()] = operation;
  }

  return {
    openapi: '3.1.0',
    info: {
      title: 'N409 Client API',
      version: input.version,
      description:
        'Every endpoint the web application and the firm workspace call. Generated from the route ' +
        'table this service registers, so the inventory is exact; request and response bodies are ' +
        'validated inside the handlers rather than by a route schema, so this document describes ' +
        'them only at the tag level. Failures are uniform — an RFC 9457 problem document whose ' +
        '`type` vocabulary is served at GET /api/v1/problems. The partner API is documented ' +
        'separately, with full schemas, at /api/partner/v1/openapi.json.',
    },
    servers: [{ url: '/' }],
    tags: API_TAGS.filter((tag) => usedTags.has(tag.name)),
    components: {
      securitySchemes: {
        session: {
          type: 'apiKey',
          in: 'cookie',
          name: SESSION_COOKIE,
          description: 'Session cookie set by POST /api/v1/auth/login.',
        },
        bearer: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'The same session as a bearer token, for non-browser clients.',
        },
      },
      schemas: { Problem: PROBLEM_SCHEMA },
    },
    security: [{ session: [] }, { bearer: [] }],
    paths,
  };
}
