import type pg from 'pg';
import { newUlid } from '@n409/shared';
import { withClientTransaction, withTransaction } from '../db/pool.js';
import {
  classifyTransportError,
  isTerminalBounce,
  type BounceKind,
  type DeliveryEventKind,
} from '../domain/emailDelivery.js';
import { recordEmailDeliveryEvent } from '../observability/emailDeliveryMetrics.js';
import { sliceChars } from '../domain/textSlice.js';

/**
 * The delivery ledger and the suppression list (migration 0163).
 *
 * Two rules shape every statement here, and both come from what a real
 * provider's webhook stream looks like rather than from what it ought to:
 *
 *   * events arrive more than once. A provider that does not get a 2xx inside
 *     its timeout redelivers, and it will happily redeliver something we
 *     already stored. So the ledger insert is idempotent on
 *     (source, provider_event_id) and applying an event must be safe to repeat.
 *
 *   * events arrive out of order. A bounce generated by a forwarding hop can
 *     reach us before the delivery notification from the first hop. So the
 *     outbox columns are folded, never assigned: the earliest delivery wins,
 *     the latest open wins, and the strongest bounce wins. Assigning would make
 *     the final state depend on webhook scheduling, which is the kind of bug
 *     that reproduces once a month and never in a test.
 */

export interface DeliveryEventInput {
  outboxId: string;
  kind: DeliveryEventKind;
  occurredAt: Date;
  /** 'webhook:<provider>', 'dsn', or 'pixel'. */
  source: string;
  /** The provider's id for this event; null for signals that have none. */
  providerEventId?: string | null;
  bounceKind?: BounceKind | null;
  detail?: string | null;
}

export interface EmailDeliveryEventRow {
  id: string;
  outbox_id: string;
  kind: DeliveryEventKind;
  occurred_at: Date;
  received_at: Date;
  source: string;
  provider_event_id: string | null;
  bounce_kind: BounceKind | null;
  detail: string | null;
}

/**
 * Bounce severity as a number, so SQL can pick the stronger of two without a
 * three-way CASE at every call site. Mirrors `isTerminalBounce`: complaint is
 * the strongest signal, not the weakest, because it is the one that costs us a
 * sending domain.
 */
const BOUNCE_RANK: Record<BounceKind, number> = { soft: 1, hard: 2, complaint: 3 };

/**
 * Records an event and folds it into the outbox row, in one transaction.
 *
 * Returns false when the event was a duplicate the ledger already had — the
 * caller answers 2xx either way (a provider redelivering must be told to stop),
 * but the distinction is worth having in the logs and in the tests.
 *
 * The fold happens only on a fresh insert. Re-folding a duplicate would be
 * harmless for the timestamps, which are idempotent, and wrong for `open_count`
 * — a provider redelivering one open five times would report five opens.
 */
export async function recordDeliveryEvent(
  db: pg.Pool | pg.PoolClient,
  input: DeliveryEventInput,
): Promise<boolean> {
  const run = async (tx: pg.PoolClient): Promise<boolean> => {
    const inserted = await tx.query(
      `INSERT INTO email_delivery_events
         (id, outbox_id, kind, occurred_at, source, provider_event_id, bounce_kind, detail)
       VALUES ($1, $2, $3::email_delivery_event_kind, $4, $5, $6, $7::email_bounce_kind, $8)
       ON CONFLICT (source, provider_event_id) DO NOTHING
       RETURNING id`,
      [
        newUlid(),
        input.outboxId,
        input.kind,
        input.occurredAt,
        input.source,
        input.providerEventId ?? null,
        input.bounceKind ?? null,
        input.detail ?? null,
      ],
    );
    if (inserted.rowCount === 0) return false;
    await applyEvent(tx, input);
    return true;
  };

  // The send paths differ in what they hold: the retry sweep and the webhook
  // route have the pool, while the auto-email sweep is already holding one
  // client for its whole pass and taking a second from the same pool to record
  // a bounce is how a sweep deadlocks itself against its own pool ceiling.
  const fresh = isPool(db) ? await withTransaction(db, run) : await withClientTransaction(db, run);
  // Counted on a fresh insert only, same as `applied` in the webhook route: a
  // provider redelivering a batch it never got a 2xx for must not report the
  // same complaint or bounce again every time it retries.
  if (fresh) recordEmailDeliveryEvent(input.kind, resolvedBounceKind(input));
  return fresh;
}

/** `pg.Pool` has `connect`; a `PoolClient` has `release`. */
function isPool(db: pg.Pool | pg.PoolClient): db is pg.Pool {
  return typeof (db as pg.PoolClient).release !== 'function';
}

/**
 * The bounce kind a 'bounced'/'complained' event carries, applying the same
 * default `applyEvent` folds into the row — read here too, so the metric and
 * the column can never disagree about what an unclassified event meant.
 */
function resolvedBounceKind(input: DeliveryEventInput): BounceKind | null {
  if (input.kind !== 'bounced' && input.kind !== 'complained') return null;
  return input.bounceKind ?? (input.kind === 'complained' ? 'complaint' : 'hard');
}

/**
 * Folds one event into the outbox row's derived columns.
 *
 * Every assignment is a fold over the current value, so applying the same
 * event twice, or two events in either order, lands on the same row.
 */
async function applyEvent(client: pg.PoolClient, input: DeliveryEventInput): Promise<void> {
  switch (input.kind) {
    case 'delivered':
      // The earliest confirmation is the delivery; a later one is a duplicate
      // hop reporting the same arrival.
      await client.query(
        `UPDATE email_outbox
            SET delivered_at = LEAST(COALESCE(delivered_at, $2::timestamptz), $2::timestamptz)
          WHERE id = $1`,
        [input.outboxId, input.occurredAt],
      );
      return;

    case 'opened':
      await client.query(
        `UPDATE email_outbox
            SET first_opened_at = LEAST(COALESCE(first_opened_at, $2::timestamptz), $2::timestamptz),
                last_opened_at  = GREATEST(COALESCE(last_opened_at, $2::timestamptz), $2::timestamptz),
                open_count      = open_count + 1,
                -- An open is proof of delivery that no delivery notification
                -- was needed for. Providers that report opens but not
                -- deliveries are common, and a message nobody can call
                -- delivered but somebody demonstrably read would otherwise sit
                -- in the stats as merely 'sent'.
                delivered_at    = LEAST(COALESCE(delivered_at, $2::timestamptz), $2::timestamptz)
          WHERE id = $1`,
        [input.outboxId, input.occurredAt],
      );
      return;

    case 'bounced':
    case 'complained': {
      const kind = resolvedBounceKind(input)!;
      await client.query(
        `UPDATE email_outbox
            SET bounced_at = LEAST(COALESCE(bounced_at, $2::timestamptz), $2::timestamptz),
                -- The stronger bounce wins, so a soft bounce arriving after a
                -- hard one cannot un-suppress an address.
                bounce_kind = CASE
                  WHEN bounce_kind IS NULL THEN $3::email_bounce_kind
                  WHEN $4::int > (CASE bounce_kind
                                    WHEN 'soft' THEN 1 WHEN 'hard' THEN 2 ELSE 3 END)
                    THEN $3::email_bounce_kind
                  ELSE bounce_kind
                END,
                bounce_detail = COALESCE($5, bounce_detail)
          WHERE id = $1`,
        [input.outboxId, input.occurredAt, kind, BOUNCE_RANK[kind], input.detail ?? null],
      );
      return;
    }

    case 'deferred':
      // A deferral is the relay saying "later", which is exactly what the 0159
      // ladder already does. Recorded in the ledger for the operator, and
      // deliberately not folded into any column: it changes nothing about the
      // row's state and overwriting `error` with it would bury the real reason.
      return;
  }
}

/**
 * Classifies a transport failure and, when it is terminal, stops the ladder.
 *
 * Called by every send path after it has marked the row failed. A no-op unless
 * the transport gave us grounds — an unclassifiable error (timeout, DNS, a bug)
 * leaves the row on the 0159 ladder, which is what the ladder is for.
 *
 * When the relay permanently rejected the *recipient*, three things follow and
 * all three matter:
 *
 *   * `bounce_kind` on the row, which takes it out of the retry claim. Without
 *     this a dead address spends six attempts over eight and a half hours.
 *   * a ledger entry, so the operator sees why it stopped rather than a row
 *     that simply never retried.
 *   * the address on the suppression list, so the *next* message to it is not
 *     another six attempts. This is the half that protects sending reputation.
 *
 * Returns the classification, or null when nothing was recorded.
 */
export async function recordSendFailure(
  db: pg.Pool | pg.PoolClient,
  email: { id: string; to_email: string },
  err: unknown,
): Promise<BounceKind | null> {
  const kind = classifyTransportError(err);
  // A soft classification is exactly the ladder's default behaviour, so there
  // is nothing to write: recording it would only mark the row as bounced and
  // take it out of the retry it should stay in.
  if (kind === null || !isTerminalBounce(kind)) return kind;

  const detail = sliceChars(err instanceof Error ? err.message : String(err), 500);
  const occurredAt = new Date();

  await recordDeliveryEvent(db, {
    outboxId: email.id,
    kind: kind === 'complaint' ? 'complained' : 'bounced',
    occurredAt,
    source: 'smtp',
    // The relay told us inside the send. There is no provider event id, and
    // two such rejections of the same message are two real events.
    providerEventId: null,
    bounceKind: kind,
    detail,
  });

  await suppressAddress(db, {
    address: email.to_email,
    reason: kind,
    detail,
    outboxId: email.id,
  });

  return kind;
}

/** The events behind one message, newest first. */
export async function listDeliveryEvents(
  pool: pg.Pool,
  outboxId: string,
  limit = 50,
): Promise<EmailDeliveryEventRow[]> {
  const { rows } = await pool.query<EmailDeliveryEventRow>(
    `SELECT * FROM email_delivery_events
      WHERE outbox_id = $1
      ORDER BY occurred_at DESC, received_at DESC
      LIMIT $2`,
    [outboxId, Math.min(limit, 500)],
  );
  return rows;
}

/* ------------------------------------------------------------------ *
 * Suppression list
 * ------------------------------------------------------------------ */

export interface SuppressionRow {
  to_email: string;
  reason: BounceKind;
  detail: string | null;
  outbox_id: string | null;
  created_at: Date;
  released_at: Date | null;
  released_by: string | null;
}

/**
 * Addresses are compared case-insensitively.
 *
 * The local part is technically case-sensitive per RFC 5321, and no mail system
 * anybody uses honours that. Suppressing `Client@Example.com` and then sending
 * to `client@example.com` would defeat the list on a difference that does not
 * exist in practice, so the key is folded on the way in and on the way out.
 */
function normalizeAddress(address: string): string {
  return address.trim().toLowerCase();
}

/** True when this address is currently suppressed (a released row is not). */
export async function isSuppressed(
  db: pg.Pool | pg.PoolClient,
  address: string,
): Promise<SuppressionRow | null> {
  const { rows } = await db.query<SuppressionRow>(
    `SELECT * FROM email_suppressions WHERE to_email = $1 AND released_at IS NULL`,
    [normalizeAddress(address)],
  );
  return rows[0] ?? null;
}

/**
 * Adds an address to the list, or strengthens an existing entry.
 *
 * A re-suppression of an already-suppressed address refreshes the reason only
 * when the new one is stronger, for the same reason the bounce fold does: a
 * soft signal must not downgrade a hard one. Re-suppressing a *released*
 * address clears the release — an admin's "try this again" is not a permanent
 * exemption, and a second hard bounce is the address answering them.
 */
export async function suppressAddress(
  db: pg.Pool | pg.PoolClient,
  input: { address: string; reason: BounceKind; detail?: string | null; outboxId?: string | null },
  opts: {
    /**
     * Write only when the address has no suppression row at all.
     *
     * For the caller that is finishing an operation that stopped half-way: the
     * delivery event committed, the suppression it should have caused did not,
     * and the provider's redelivery is the only chance to notice — but by then
     * the event is a duplicate, so it is no longer evidence of a *new* bounce.
     * An existing row is therefore left exactly as it is, released or not,
     * because clearing an administrator's release needs a bounce that has not
     * already been counted. See the webhook route.
     */
    onlyIfAbsent?: boolean;
  } = {},
): Promise<void> {
  if (opts.onlyIfAbsent) {
    await db.query(
      `INSERT INTO email_suppressions (to_email, reason, detail, outbox_id)
       VALUES ($1, $2::email_bounce_kind, $3, $4)
       ON CONFLICT (to_email) DO NOTHING`,
      [normalizeAddress(input.address), input.reason, input.detail ?? null, input.outboxId ?? null],
    );
    return;
  }
  await db.query(
    `INSERT INTO email_suppressions (to_email, reason, detail, outbox_id)
     VALUES ($1, $2::email_bounce_kind, $3, $4)
     ON CONFLICT (to_email) DO UPDATE
       SET reason = CASE
             WHEN $5::int > (CASE email_suppressions.reason
                               WHEN 'soft' THEN 1 WHEN 'hard' THEN 2 ELSE 3 END)
               THEN EXCLUDED.reason
             ELSE email_suppressions.reason
           END,
           detail      = COALESCE(EXCLUDED.detail, email_suppressions.detail),
           outbox_id   = COALESCE(EXCLUDED.outbox_id, email_suppressions.outbox_id),
           released_at = NULL,
           released_by = NULL`,
    [
      normalizeAddress(input.address),
      input.reason,
      input.detail ?? null,
      input.outboxId ?? null,
      BOUNCE_RANK[input.reason],
    ],
  );
}

/**
 * Lifts a suppression. The row stays, so "this was suppressed and an admin
 * lifted it on Tuesday" survives the lifting.
 */
export async function releaseSuppression(
  pool: pg.Pool,
  address: string,
  releasedBy: string,
): Promise<boolean> {
  const { rowCount } = await pool.query(
    `UPDATE email_suppressions
        SET released_at = now(), released_by = $2
      WHERE to_email = $1 AND released_at IS NULL`,
    [normalizeAddress(address), releasedBy],
  );
  return (rowCount ?? 0) > 0;
}

export const SUPPRESSION_PAGE_LIMIT = 500;

/**
 * The cap reports itself, like every other list on the platform.
 *
 * It was a bare `LIMIT $1` returning a bare array, which is the one shape both
 * cap censuses are blind to: `silentCapCensus` skips a parameterised limit
 * because that is normally where the flag lives, and the frontend's truncation
 * census keys on a flag being present, so an endpoint with none is not a
 * truncating endpoint as far as it can tell. Between them an address that fell
 * off the end of this list was an address nobody would find and nobody could
 * release — and the whole reason to read this list is to release something.
 */
export async function listSuppressions(
  pool: pg.Pool,
  opts: { includeReleased?: boolean; limit?: number } = {},
): Promise<{ suppressions: SuppressionRow[]; truncated: boolean }> {
  const limit = Math.min(Math.max(opts.limit ?? 100, 1), SUPPRESSION_PAGE_LIMIT);
  const { rows } = await pool.query<SuppressionRow>(
    `SELECT * FROM email_suppressions
      ${opts.includeReleased ? '' : 'WHERE released_at IS NULL'}
      ORDER BY created_at DESC
      LIMIT $1`,
    [limit + 1],
  );
  return { suppressions: rows.slice(0, limit), truncated: rows.length > limit };
}

/* ------------------------------------------------------------------ *
 * Reporting
 * ------------------------------------------------------------------ */

export interface DeliveryStats {
  window_days: number;
  total: number;
  queued: number;
  sent: number;
  failed: number;
  skipped: number;
  delivered: number;
  bounced: number;
  complained: number;
  opened: number;
  suppressed_addresses: number;
}

/**
 * One pass over the window for the dashboard.
 *
 * Counts rather than rates: whether a denominator is large enough to express as
 * a percentage is `rateOrNull`'s decision in the domain, and doing it here
 * would put a presentation rule in SQL where the tests cannot reach it.
 */
export async function deliveryStats(pool: pg.Pool, windowDays: number): Promise<DeliveryStats> {
  const { rows } = await pool.query<Record<string, string>>(
    `SELECT
       count(*)                                                       AS total,
       count(*) FILTER (WHERE status = 'queued')                      AS queued,
       count(*) FILTER (WHERE status = 'sent')                        AS sent,
       count(*) FILTER (WHERE status = 'failed')                      AS failed,
       count(*) FILTER (WHERE status = 'skipped')                     AS skipped,
       count(*) FILTER (WHERE delivered_at IS NOT NULL)               AS delivered,
       count(*) FILTER (WHERE bounced_at IS NOT NULL
                          AND bounce_kind IS DISTINCT FROM 'complaint') AS bounced,
       count(*) FILTER (WHERE bounce_kind = 'complaint')              AS complained,
       count(*) FILTER (WHERE first_opened_at IS NOT NULL)            AS opened
     FROM email_outbox
     WHERE created_at >= now() - make_interval(days => $1::int)`,
    [windowDays],
  );
  const row = rows[0] ?? {};
  const n = (key: string): number => Number.parseInt(row[key] ?? '0', 10) || 0;

  const { rows: sup } = await pool.query<{ count: string }>(
    `SELECT count(*) AS count FROM email_suppressions WHERE released_at IS NULL`,
  );

  return {
    window_days: windowDays,
    total: n('total'),
    queued: n('queued'),
    sent: n('sent'),
    failed: n('failed'),
    skipped: n('skipped'),
    delivered: n('delivered'),
    bounced: n('bounced'),
    complained: n('complained'),
    opened: n('opened'),
    suppressed_addresses: Number.parseInt(sup[0]?.count ?? '0', 10) || 0,
  };
}

/** Per-template breakdown, for finding the one workflow mail that bounces. */
export interface TemplateDeliveryStats {
  template_key: string;
  total: number;
  delivered: number;
  bounced: number;
  failed: number;
}

export async function deliveryStatsByTemplate(
  pool: pg.Pool,
  windowDays: number,
  limit = 50,
): Promise<TemplateDeliveryStats[]> {
  const { rows } = await pool.query<Record<string, string>>(
    `SELECT template_key,
            count(*)                                          AS total,
            count(*) FILTER (WHERE delivered_at IS NOT NULL)  AS delivered,
            count(*) FILTER (WHERE bounced_at IS NOT NULL)    AS bounced,
            count(*) FILTER (WHERE status = 'failed')         AS failed
       FROM email_outbox
      WHERE created_at >= now() - make_interval(days => $1::int)
      GROUP BY template_key
      ORDER BY count(*) DESC
      LIMIT $2`,
    [windowDays, Math.min(limit, 200)],
  );
  return rows.map((r) => ({
    template_key: r.template_key ?? '',
    total: Number.parseInt(r.total ?? '0', 10) || 0,
    delivered: Number.parseInt(r.delivered ?? '0', 10) || 0,
    bounced: Number.parseInt(r.bounced ?? '0', 10) || 0,
    failed: Number.parseInt(r.failed ?? '0', 10) || 0,
  }));
}
