import type pg from 'pg';
import { newUlid } from '@n409/shared';
import type { ValuationEventType } from '../domain/auditTrail.js';

/**
 * The audit spine (architecture §1: "everything is an event on the Valuation").
 * Events are written in the SAME transaction as the change they describe, so a
 * change without its event (or vice versa) is impossible.
 */
export interface EventActor {
  actorType: 'human' | 'ai' | 'engine' | 'system';
  actorId?: string | null;
  source?: string;
}

export interface ValuationEventRow {
  id: string;
  valuation_id: string;
  seq: string;
  type: string;
  actor_type: string;
  actor_id: string | null;
  source: string | null;
  payload: Record<string, unknown>;
  occurred_at: Date;
}

/**
 * Append one event.
 *
 * `type` is the catalog's key union rather than `string`: the audit trail
 * describes an event by looking its type up in `EVENT_CATALOG`, and a type with
 * no entry there renders as "Event recorded" in the change log and the evidence
 * bundle. Taking the union means the missing descriptor is a compile error here
 * instead of a vague line in an auditor's export.
 */
export async function recordEvent(
  client: pg.PoolClient,
  args: {
    valuationId: string;
    type: ValuationEventType;
    actor: EventActor;
    payload?: Record<string, unknown>;
  },
): Promise<ValuationEventRow> {
  const { rows } = await client.query<ValuationEventRow>(
    `INSERT INTO valuation_events (id, valuation_id, type, actor_type, actor_id, source, payload)
     VALUES ($1, $2, $3, $4, $5, $6, $7)
     RETURNING *`,
    [
      newUlid(),
      args.valuationId,
      args.type,
      args.actor.actorType,
      args.actor.actorId ?? null,
      args.actor.source ?? 'api',
      JSON.stringify(args.payload ?? {}),
    ],
  );
  return rows[0]!;
}

/**
 * Append many events in one statement.
 *
 * The spine is one row per thing that happened and nothing about that changes
 * here — what changes is the number of round trips it takes to write a set of
 * them that is already known in full.
 *
 * WHY (round 351, methodology M8). `releaseAssignedWork` runs inside the
 * transaction that closes an account, and wrote one of these per released
 * engagement and per released task, awaited one at a time. The two `UPDATE …
 * RETURNING` statements above it are set-based and take a row lock on every
 * engagement they touch — and `assigned_reviewer_id` is in `OPS_PATCH_FIELDS`,
 * so each also bumps `version`. Every one of those locks was then held for the
 * whole serial run of inserts: a reviewer holding three hundred live
 * engagements meant three hundred round trips of an open write transaction with
 * three hundred engagements locked inside it, where the work is one statement.
 * A directory resync deactivates a department at a time, so the batches arrive
 * together.
 *
 * `unnest` rather than a built-up `VALUES` list: one prepared statement shape
 * whatever the batch size, so the driver's plan cache is not filled with a
 * variant per length, and seven parameters rather than seven per row.
 *
 * Ordering is preserved. `seq` is `GENERATED BY DEFAULT AS IDENTITY`, and a
 * multi-row INSERT draws from the sequence in the order the rows are fed, so
 * the events of one batch keep the order they were built in — which is the
 * order `recordEvent` in a loop gave them.
 *
 * Returns nothing: the row a caller of {@link recordEvent} gets back is used by
 * exactly the callers that want it, and a batch writer has no reader.
 */
export async function recordEvents(
  client: pg.PoolClient,
  events: ReadonlyArray<{
    valuationId: string;
    type: ValuationEventType;
    actor: EventActor;
    payload?: Record<string, unknown>;
  }>,
): Promise<void> {
  if (events.length === 0) return;
  await client.query(
    `INSERT INTO valuation_events (id, valuation_id, type, actor_type, actor_id, source, payload)
     SELECT * FROM unnest(
       $1::ulid[], $2::ulid[], $3::text[], $4::actor_type[], $5::text[], $6::text[], $7::jsonb[]
     )`,
    [
      events.map(() => newUlid()),
      events.map((e) => e.valuationId),
      events.map((e) => e.type),
      events.map((e) => e.actor.actorType),
      events.map((e) => e.actor.actorId ?? null),
      events.map((e) => e.actor.source ?? 'api'),
      events.map((e) => JSON.stringify(e.payload ?? {})),
    ],
  );
}

/**
 * Ceiling on one read of the raw spine (`GET /valuations/:id/events`).
 *
 * Smaller than the audit trail's MAX_TRAIL_EVENTS because this route hands
 * back whole rows — `payload` included, unsummarised — where the trail hands
 * back a described entry. It is a bound on one response, not on the history:
 * the trail route pages through all of it.
 */
export const EVENT_PAGE_LIMIT = 1_000;

/**
 * Filters pushed down to SQL. A long-running valuation accumulates thousands
 * of events; readers that only care about a slice (the client timeline, one
 * event type, a date window) should not drag the whole spine into memory.
 * Every predicate here is served by an index from 0001/0047 —
 * (valuation_id, occurred_at), (type), (actor_id, occurred_at).
 */
export interface EventQuery {
  /** Restrict to these event types. An empty array matches nothing. */
  types?: readonly string[];
  actorType?: string;
  actorId?: string;
  from?: Date;
  to?: Date;
  /** Cap the number of rows returned (newest kept, order still ascending). */
  limit?: number;
}

export async function listEvents(
  pool: pg.Pool,
  valuationId: string,
  query: EventQuery = {},
): Promise<ValuationEventRow[]> {
  const where = ['valuation_id = $1'];
  const params: unknown[] = [valuationId];
  const add = (clause: string, value: unknown) => {
    params.push(value);
    where.push(clause.replace('?', `$${params.length}`));
  };
  if (query.types) add('type = ANY(?)', [...query.types]);
  if (query.actorType) add('actor_type = ?', query.actorType);
  if (query.actorId) add('actor_id = ?', query.actorId);
  if (query.from) add('occurred_at >= ?', query.from);
  if (query.to) add('occurred_at <= ?', query.to);

  // The newest N rows, handed back oldest-first so callers can keep reading
  // the spine in causal order.
  if (query.limit !== undefined) {
    params.push(query.limit);
    const { rows } = await pool.query<ValuationEventRow>(
      `SELECT * FROM (
         SELECT * FROM valuation_events WHERE ${where.join(' AND ')}
         ORDER BY seq DESC LIMIT $${params.length}
       ) recent ORDER BY seq ASC`,
      params,
    );
    return rows;
  }

  const { rows } = await pool.query<ValuationEventRow>(
    `SELECT * FROM valuation_events WHERE ${where.join(' AND ')} ORDER BY seq ASC`,
    params,
  );
  return rows;
}

/** When anything last happened on this valuation — an index-only lookup. */
export async function latestEventAt(pool: pg.Pool, valuationId: string): Promise<Date | null> {
  const { rows } = await pool.query<{ occurred_at: Date }>(
    'SELECT occurred_at FROM valuation_events WHERE valuation_id = $1 ORDER BY occurred_at DESC LIMIT 1',
    [valuationId],
  );
  return rows[0]?.occurred_at ?? null;
}

/**
 * When the valuation first entered each state it has ever been in.
 *
 * The progress stepper needs the *earliest* `state_changed` into each stage,
 * and every other read of this spine keeps the *newest* rows — which is why
 * this was the one caller that could not take a page and so took the whole
 * history instead. `listEvents(pool, id, { types: ['state_changed'] })` is
 * unbounded by construction: a valuation that bounces between review and
 * revision accumulates a `state_changed` per bounce, for as long as the
 * engagement runs, and the route dragged all of them into memory to keep at
 * most one per stage.
 *
 * So the bound is the question rather than a cap: `DISTINCT ON` over the target
 * state returns one row per state the valuation has been in, and the states are
 * an enum — `ValuationState`, a dozen of them. That is a bound the schema
 * states, not a page size, so the answer is the same one the full read gave.
 */
export async function firstEntryPerState(pool: pg.Pool, valuationId: string): Promise<Map<string, Date>> {
  const { rows } = await pool.query<{ to_state: string; occurred_at: Date }>(
    `SELECT DISTINCT ON (payload->>'to') payload->>'to' AS to_state, occurred_at
       FROM valuation_events
      WHERE valuation_id = $1 AND type = 'state_changed' AND payload->>'to' IS NOT NULL
      ORDER BY payload->>'to', seq ASC`,
    [valuationId],
  );
  return new Map(rows.map((r) => [r.to_state, r.occurred_at]));
}
